Mongo#2
gowthamrodda/mango-mongo pull request #4
Opened 2019-09-25 13:08 UTC by yashraj20

2019-09-27 09:58 UTC, yashraj20 commented
created separate connection file

2019-09-27 10:01 UTC, gowthamrodda commented
@yashraj20 Configuration needs to be separated, for example the port number and mongo host should come from config file.

2019-09-27 10:02 UTC, gowthamrodda requested changes

2019-09-27 10:02 UTC, gowthamrodda commented on src/connection.ts
> +
@yashraj20 Connection is opened but not closed.

2019-09-27 11:43 UTC, gowthamrodda commented
```
let con = async function connect(url): Connection {
if(url) {
return mongo.connect(url, {useNewUrlParser: true,useUnifiedTopology: true});
}
}
async function disconnect(con: Connection) {
 await con.close();
}
```
export {con, disconnect};

2019-10-03 08:50 UTC, gowthamrodda approved these changes

2019-10-03 09:28 UTC, gowthamrodda requested changes
Please solve conflicts

2019-10-04 10:05 UTC, closed without merging